### PR TITLE
feat: workspace updates

### PR DESCRIPTION
**Pull request by NathanWalker**
- several workspace updates including {N} 8.8, Nx 19+, TS 5.5, several transient dep updates (including glob), tailwind for demo apps

### CODE REVIEW

**Comment by NathanWalker** [comment]
@ammarahm-ed I've pushed up some nice cleanups just now to get this in good shape. Fully works on iOS.
Android has this remaining case if get a chance to check:
```
packages/core/react-android/bridge/src/main/java/com/bridge/Packages.java:38: error: TurboReactPackage is abstract; cannot be instantiated
      new TurboReactPackage(),
      ^
```

When trying this branch, best to:
```bash
// ensure using latest cli
npm install -g nativescript@latest

// ensure all deps are reset
yarn setup

// ensure demo hooks are regenerated
yarn demo:hooks

// now run android demo
yarn nx run demo:android
```

**Comment by ammarahm-ed** [comment]
@NathanWalker I will try to fix it today.

**Comment by NathanWalker** [comment]
@ammarahm-ed sorry for inconvenience realized tailwind.config was being gitignored, latest push fixes that.

**Comment by ammarahm-ed** [comment]
Hey @NathanWalker just fixed the issue on android. let me know if it's ready to merge. Both android & ios are building now.

**Review by ammarahm-ed — APPROVED** [review]

**Comment by NathanWalker** [comment]
Awesome @ammarahm-ed i think this can become final 2.0 (no more alpha) 🎉

**Pull request merged**
